{% set name = "laserfields" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/laserfields-{{ version }}.tar.gz
  sha256: b3f30b6e5ca86176b94d5e594342502feccfc06ffef54bf4798b837096973bd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - numpy >=1.15
    - scipy >=1.0
    - numba >=0.49

test:
  imports:
    - laserfields
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python library for describing time-dependent laserfields by Johannes Feist.
  license: MIT
  license_file: LICENSE
  home: https://github.com/jfeist/pylaserfields

extra:
  recipe-maintainers:
    - jfeist
